spring:
  application:
    name: ms-account
  datasource:
    url: jdbc:mysql://localhost:3307/foo_fighters
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true                     # разрешает делать изменения через Liquibase файл
server:
  port: 8080